AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A starter SAM CodePipeline.


Parameters:
  GithubRepo:
    Description: Gitub Repository name
    Type: String

  GithubToken:
    Description: Github OAuth Token with full permissions on admin:repo_hook and repo
    Type: String

  GithubUser:
    Description: Github user where the repository lives
    Type: String



Resources:

 ######   #######  ##     ## ########   ######  ######## 
##    ## ##     ## ##     ## ##     ## ##    ## ##       
##       ##     ## ##     ## ##     ## ##       ##       
 ######  ##     ## ##     ## ########  ##       ######   
      ## ##     ## ##     ## ##   ##   ##       ##       
##    ## ##     ## ##     ## ##    ##  ##    ## ##       
 ######   #######   #######  ##     ##  ######  ######## 

  BuildArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain